title = "Grant Swift"
baseURL = "https://grantswiftmusic.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main" #
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[[menu.main]]
  name = "Shows"
  weight = -115
  identifier = "shows"
  url = "/show"

  [[menu.main]]
    name = "Posts"
    weight = -110
    identifier = "posts"
    url = "/post"

[[menu.main]]
  name = "Bio"
  weight = -105
  identifier = "bio"
  url = "/page/bio/"

[[menu.main]]
  name = "Private Events"
  weight = -100
  identifier = "private-events"
  url = "/page/private-events/"

[[menu.main]]
  name = "Compositions"
  weight = -95
  identifier = "compositions"
  url = "https://grantswift.bandcamp.com/"

[[menu.main]]
  name = "Contact"
  weight = -90
  identifier = "contact"
  url = "/page/contact/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last musician you'll ever need. Maybe."
  facebook = "https://www.facebook.com/grantswiftmusic/"
  twitter = "https://twitter.com/grantswiftmusic"
  instagram = "https://www.instagram.com/grantswiftmusic/"
  youtube = "https://www.youtube.com/channel/UC6b_wOzvz8F-n7eIZp_EQxQ"
  github = ""
  linkedin = ""
  background_color_class = "bg-black"
  featured_image = "/images/swifthome.jpg"
  mainSections = ["post","show"]
  body_classes = "avenir bg-near-white"
