title = "Grant Swift"
baseURL = "https://grantswiftmusic.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main" #
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
  name = "Shows"
  weight = -115
  identifier = "shows"
  url = "/page/shows/"

#below section is treated like "post" or blog entry. Note the url does not have /page

#[[menu.main]]
  #name = "Shows"
  #weight = -115
  #identifier = "shows"
  #url = "/show"

[[menu.main]]
  name = "Posts"
  weight = -110
  identifier = "posts"
  url = "/post"

[[menu.main]]
  name = "Bio/EPK"
  weight = -105
  identifier = "bio"
  url = "/page/bio/"

[[menu.main]]
  name = "Private Events"
  weight = -100
  identifier = "private-events"
  url = "/page/private-events/"

[[menu.main]]
  name = "Compositions"
  weight = -95
  identifier = "compositions"
  url = "https://distrokid.com/hyperfollow/grantswift/fear-and-love-in-the-time-of-corona" target="_blank"

[[menu.main]]
  name = "Sign Up"
  weight = -90
  identifier = "sign-up"
  url = "/page/sign-up/"

[[menu.main]]
  name = "Contact"
  weight = -85
  identifier = "contact"
  url = "/page/contact/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last musician you'll ever need. Maybe."
  facebook = "https://www.facebook.com/grantswiftmusic/"
  twitter = "https://twitter.com/grantswiftmusic"
  instagram = "https://www.instagram.com/grantswiftmusic/"
  youtube = "https://www.youtube.com/channel/UC6b_wOzvz8F-n7eIZp_EQxQ"
  github = ""
  linkedin = ""
  background_color_class = "bg-black"
  featured_image = "/images/swifthome.jpg"
  mainSections = ["post",]
  body_classes = "avenir bg-near-white"
