title = "Grant Swift Glidden"
baseURL = "https://swiftglidden.com"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[[menu.main]]
  name = "Bio"
  weight = -110
  identifier = "bio"
  url = "/page/bio/"

[[menu.main]]
  name = "Original Music"
  weight = -100
  identifier = "original-music"
  url = "https://swiftglidden.bandcamp.com/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last musician you'll ever need. Maybe."
  facebook = "https://www.facebook.com/swiftglidden/"
  twitter = "https://twitter.com/SwiftGlidden"
  instagram = "https://www.instagram.com/swiftglidden/"
  youtube = "https://www.youtube.com/channel/UC6b_wOzvz8F-n7eIZp_EQxQ"
  github = ""
  linkedin = ""
  background_color_class = "bg-black"
  featured_image = "/images/swifthome.jpg"
